"""file table

Revision ID: 183d95ded5e8
Revises: e3625d9643ce
Create Date: 2025-06-13 02:24:51.722028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183d95ded5e8'
down_revision = 'e3625d9643ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.Enum('MAIN_IMAGE', 'SCREENSHOT', 'SOURCE', name='filetype'), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_files_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_name', name=op.f('uq_files_storage_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
