"""enum file type

Revision ID: 194dee641040
Revises: e3625d9643ce
Create Date: 2025-06-15 01:14:50.730697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194dee641040'
down_revision = 'e3625d9643ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.Enum('main_image', 'screenshot', 'source'), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_files_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_name', name=op.f('uq_files_storage_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
