"""visit logs

Revision ID: 1e229d182346
Revises: 194dee641040
Create Date: 2025-06-18 00:52:18.090752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e229d182346'
down_revision = '194dee641040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_logs')
    # ### end Alembic commands ###
