"""game stats

Revision ID: 377cff1d447b
Revises: 1796da2bc874
Create Date: 2025-06-19 22:19:58.984727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377cff1d447b'
down_revision = '1796da2bc874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_games_stats_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_games_stats'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_stats')
    # ### end Alembic commands ###
