"""role_name is foreign key in user model

Revision ID: 66f60ef41f60
Revises: 68933cd000d7
Create Date: 2025-05-22 23:09:32.506150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66f60ef41f60'
down_revision = '68933cd000d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_role_name_roles'), 'roles', ['role_name'], ['name'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_users_role_name_roles'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
