"""initial

Revision ID: 68933cd000d7
Revises: 
Create Date: 2025-05-22 22:20:36.553138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68933cd000d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('info',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=40),
               nullable=False)
        batch_op.drop_column('display_name')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
