"""visit log on cascade set null

Revision ID: 7b95d1543052
Revises: ab627dbe10ff
Create Date: 2025-06-20 16:07:48.976172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b95d1543052'
down_revision = 'ab627dbe10ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_logs_user_id_users'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_logs_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
