"""OS games back_poplates os_list

Revision ID: d026e8f1cd66
Revises: 66f60ef41f60
Create Date: 2025-06-01 22:34:51.538241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd026e8f1cd66'
down_revision = '66f60ef41f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('fa_icon_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_os')),
    sa.UniqueConstraint('name', name=op.f('uq_os_name'))
    )
    op.create_table('games_os',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_games_os_game_id_games')),
    sa.ForeignKeyConstraint(['os_id'], ['os.id'], name=op.f('fk_games_os_os_id_os')),
    sa.PrimaryKeyConstraint('game_id', 'os_id', name=op.f('pk_games_os'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    op.drop_table('games_os')
    op.drop_table('os')
    # ### end Alembic commands ###
