"""gamo_os cascade

Revision ID: e3625d9643ce
Revises: c24d91ca53f1
Create Date: 2025-06-13 01:50:29.802121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3625d9643ce'
down_revision = 'c24d91ca53f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games_os', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_os_game_id_games'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_games_os_game_id_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games_os', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_os_game_id_games'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_games_os_game_id_games'), 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###
