"""user FK role_name to role_id

Revision ID: eba2c1b1c1ee
Revises: 377cff1d447b
Create Date: 2025-06-20 14:03:14.851949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eba2c1b1c1ee'
down_revision = '377cff1d447b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_users_role_name_roles'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_role_name_roles'), 'roles', ['role_name'], ['name'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
